controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/user/authenticate/

api_refresh_token:
    path: /api/user/refresh/